### ISSUE TITLE
Make uniq name for http server

### ISSUE THREAD

**Issue by vgulaev** [vgulaev/rmsvet.ru#15]

**Comment by movis08** [comment]
ezsp_py_srv:версия? ))

**Comment by vgulaev** [comment]
EazyWebServer, EWC 0.1alfa

**Comment by movis08** [comment]
Звучит лучше))
Только с alfa не согласен. Он ведь уже работает. И покупатели с ним взаимодействуют. Значит не ниже beta)

**Comment by movis08** [comment]
Звучит лучше))
Только с alfa не согласен. Он ведь уже работает. И покупатели с ним взаимодействуют. Значит не ниже beta)

**Comment by vgulaev** [comment]
Хорошо! Добавляем меняем на бета.

**Comment by movis08** [comment]
http response header server name

**Comment by movis08** [comment]
Служебная информация XD
http response header server name

**Comment by movis08** [comment]
Done

**Comment by movis08** [comment]
Рано радовался)
