### ISSUE TITLE
b2b integration: Catch "SQL error happen" and print partners ID

### ISSUE THREAD

**Issue by vgulaev** [vgulaev/rmsvet.ru#9]
Fird the cause why it is happen.
And fix it!

**Comment by movis08** [comment]
Проблема в не соответствии типов!
Если точнее, то при создании объекта (для записи его в таблицу товаров) некоторые поля у него получались несоответствующего типа. В частности поле price. Которое должно быть decimal, но иногда было строкой.
Исправлено для 1С. Исправлено для OCS
